CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    username VARCHAR(64),
    ref_id BIGINT,
    wallet VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);